name: Lint Code base

on:
  push:
    branches-ignore:
      - master
  pull_request:
    branches:
      - master

jobs:
  run-linters:
    name: Run linters
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v4.1.1

      - name: Set up Python
        uses: actions/setup-python@v5.0.0
        with:
          python-version: 3.10.11

      - name: Install Python dependencies
        run: pip install black==24.2.0 flake8==7.0.0

      - name: Run linters
        uses: wearerequired/lint-action@v2.3.0
        with:
          black: true
          black_dir: apps/
          flake8: true
          flake8_dir: apps/
